[package]
name = "glass-page"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry = "0.8.0"

[dependencies.clap]
version = "3.0.0-beta.2"
features = ["wrap_help"]
